### ISSUE TITLE
Maximum sum is coming out to be wrong

### ISSUE THREAD

**Issue by thecodephilic-guy** [thecodephilic-guy/Java-DSA#1]
In the subarrays.java file under code/Array directory, the code is now giving the desigerd output. Minimum value is coming out to be correct but there's something wrong with the Max value of sum. Help me finding the issue and fix it if you know it.
Here's the link:
https://github.com/thecodephilic-guy/Java-DSA/blob/main/code/Array/subarrays.java

**Comment by Sheelendra-Sharma** [comment]
solved #1

just put the start = 0 inside the for loop so that it can set to zero after each subarray and compare with new subarray sum, if it is greater than previous one then reset it to new otherwise it will remain the same.

here is the modified code 

public class subarrays{

    public static void printSubarrays(int data[]){
        int ts = 0;
        int maxSum = Integer.MIN_VALUE;
        int minSum = Integer.MAX_VALUE;
        //outer loop:
        for(int i=0; i<data.length; i++){
            int start = i;
            //inner loop:
            for(int j=i; j<data.length; j++){
                int sum = 0;
                int end = j;
                //loop for printing:
                System.out.print("[");
                for(int k=start; k<=end; k++){
                    System.out.print(" "+data[k]+" ");
                    sum = sum + data[k];
                }
                System.out.print("] ");
                if(maxSum < sum){
                    maxSum = sum;
                }
                if(minSum > sum){
                    minSum = sum;
                }
                ts++;
            }
            System.out.println();
        }
        System.out.println("Total Subarrays: "+ts);
        System.out.println("The Max value of sum is: "+maxSum);
        System.out.println("The Min value of sum is: "+minSum);
        return;
    }

    public static void main(String[] args) {
        int data[] = {2, 4, 6, 8, 10};
        printSubarrays(data);
    }
}

**Comment by thecodephilic-guy** [comment]
Send the pull request. I'll merge it to the main branch.
